name: magic_sign
version: 1.0.0+1
publish_to: none
description: Maigc Sign
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies:

  cupertino_icons: 1.0.2
  get: 4.6.5
  intl: any
  appinio_swiper: any
  gap: any
  flutter_svg: any
  simple_animations: any
  modal_bottom_sheet: any
  curved_navigation_bar: any
  carousel_slider: any
  huawei_account: any
  agconnect_auth: 1.5.0+300
  flutter_camera: any
  path_provider: any
  video_player: any
  camera: any
  fluttertoast: any

  flutter: 
    sdk: flutter
  get_cli: ^1.7.1

dev_dependencies: 
  flutter_lints: any
  flutter_test: 
    sdk: flutter
  build_runner: any
  flutter_gen_runner: any

flutter: 
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/

